import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Jikmunn Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header>
        {/* <Image src="" alt="" /> */}
        <nav>
          <Link href="/"> Home</Link>
          <Link href="/events"> Events</Link>
          <Link href="/about"> About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <div>
          {data.map((event, idx) => (
            <a key={idx} href={`/events/${event.id}`}>
              <Image
                src={`${event.image}`}
                alt={`${event.title}`}
                width={500}
                height={400}
              />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const data = await import('/data/data.json');
  const { events_categories } = data;
  return {
    props: {
      data: events_categories,
    },
  };
}
