import Head from 'next/head';

// internal imports
import HomePage from '../src/components/Home/HomePage';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Jikmunn Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </>
  );
}

export async function getServerSideProps() {
  const data = await import('/data/data.json');
  const { events_categories } = data;
  return {
    props: {
      data: events_categories,
    },
  };
}
